#get all 
GET http://localhost:3001/products

###get Single

GET http://localhost:3001/products/67dd50c5d3c968287330dd16


###CREATE 
POST http://localhost:3001/products HTTP/1.1
Content-Type: application/json

{
  "brand": "jason",
  "model": "1235Samsung 5.G",
  "color": "black",
  "price": "299.99",
  "item": "Laptop"
}

###put contact 
PUT http://localhost:3001/products/67dd50c5d3c968287330dd16
Content-Type: application/json

{
    "brand": "new",
  "model": "xxx",
  "color": "jsfds",
  "price": "299.99",
  "item": "Laptop"
}

###Delete 
DELETE http://localhost:3001/products/67dd50c5d3c968287330dd16